#define	LSOF_BLDCMT	""
#define	LSOF_CC		"cc"
#define	LSOF_CCV	"13.0.0 (clang-1300.0.29.30)"
#define	LSOF_CCDATE	"Tue Dec 28 15:57:31 CST 2021"
#define	LSOF_CCFLAGS	"-DHASIPv6 -fno-common -mdynamic-no-pic -DHASUTMPX -DDARWINV=1800 -DHAS_STRFTIME -DLSOF_VSTR=\"20.6.0\" -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -g"
#define  LSOF_CINFO      "libproc-based"
#define	LSOF_HOST	"zhaoruideMac-mini.local"
#define	LSOF_LDFLAGS	"-L./lib -llsof  -lcurses"
#define	LSOF_LOGNAME	"zhaorui"
#define	LSOF_SYSINFO	"Darwin zhaoruideMac-mini.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64"
#define	LSOF_USER	"zhaorui"
#define	LSOF_VERSION	"4.91"
